name: 'Run rubocop with reviewdog'
description: '🐶 Run rubocop with reviewdog on pull requests to improve code review experience.'
author: 'mgrachev (reviewdog)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  rubocop_flags:
    description: 'rubocop flags. (rubocop <rubocop_flags>)'
    default: ''
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'rubocop'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    default: 'github-pr-check'
  gem_install_args:
    description: |
      List of gems passed to "gem install". Default is "rubocop" which installs latest version of rubocop.
      To install RuboCop plugins: "rubocop rubocop-rails rubocop-performance"
      To install a specific version: "rubocop:0.79.0"
    default: 'rubocop'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.rubocop_flags }}
    - ${{ inputs.tool_name }}
    - ${{ inputs.level }}
    - ${{ inputs.reporter }}
    - ${{ inputs.gem_install_args }}
branding:
  icon: 'check-circle'
  color: 'red'
